export const addTodo ="ADD_TODO"
export const removeTodo ="REMOVE_TODO"
export const doTodo ="DO_TODO"
export const filterAllTodos ="FILTER_ALL_TODOS"
export const filterCompletedTodos ="FILTER_COMPLETED_TODOS"
export const filterIncomletedTodos ="FILTER_COMPLETED_TODOS"